# Site settings
title: Macroevolution Group
description: 'Thomas lab at the University of Sheffield'
url: 'http://joshgerdes.com/jekyll-uno'
baseurl: '/ghthomas.github.io/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Gavin Thomas'
  email: gavin.thomas@sheffield.ac.uk
  twitter_username: gavothomas
  github_username:  ghthomas

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
